//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio.Core.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lab_Elementos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lab_Elementos()
        {
            this.lab_Estudios = new HashSet<lab_Estudios>();
        }
    
        public System.Guid Id { get; set; }
        public string Nombre { get; set; }
        public string UnidadMedida { get; set; }
        public string Notas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lab_Estudios> lab_Estudios { get; set; }
    }
}
