//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio.Core.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lab_Estudios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lab_Estudios()
        {
            this.lab_Elementos = new HashSet<lab_Elementos>();
            this.lab_Perfiles = new HashSet<lab_Perfiles>();
        }
    
        public System.Guid Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string Grupo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lab_Elementos> lab_Elementos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lab_Perfiles> lab_Perfiles { get; set; }
    }
}
