//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio.Core.DAL.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mmadatabaseEntities : DbContext
    {
        public mmadatabaseEntities()
            : base("name=mmadatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lab_Elementos> lab_Elementos { get; set; }
        public virtual DbSet<lab_Estudios> lab_Estudios { get; set; }
        public virtual DbSet<lab_Perfiles> lab_Perfiles { get; set; }
    }
}
